const translationsEn = {
    entries: "Today's Vehicle Entries",
    entriesyest: "Yesterdays Vehicle Entries",
    entriesweek: "Last 7 days Vehicle Entries",
    totalveh: "Total Vehicle Entries",
    totaluser: "Total Registered Users",
    lcategorie: "Listed Categories",
    cusers: "Reg Users",

    search: "Search Vehicle",
    report: "Between Dates Reports",
    rep: "Reports",
    out: "Manage Out Vehicle",
    in: "Manage In Vehicle",
    manage: "Manage vehicle",
    delete: "Delete",
    add: "Add vehicle",
    managecat: "Manage Category",
    cat: "Add category",
    addcat: "Add Category",
    
    catname: "Category Name",
    add: "Add",

    title: "VPMS - View Vehicle Detail",
    dashboard: "Dashboard",
    view_vehicle: "View Vehicle",
    incoming_vehicle: "Incoming Vehicle",
    view_incoming_vehicle: "View Incoming Vehicle",
    parking: "Parking Number",
    vehicle_category: "Vehicle Category",
    vehicle_company: "Vehicle Company Name",
    registration_number: "Registration Number",
    owner_name: "Owner Name",
    owner_contact: "Owner Contact Number",
    in_time: "In Time",
    status: "Status",
    remark: "Remark",
    parking_charge: "Parking Charge",
    outgoing_vehicle: "Outgoing Vehicle",
    update: "Update",
    parking_fee: "Parking Fee",


};